algorithm: round-robin # sticky-round-robin / url-hash / ip-hash / random
log_level: debug # info / warn / error

frontend:
  listen: 0.0.0.0:8000
#  tls:
#    cert: cert.ctr
#    key: key.key

backend:
  servers:
    - http://127.0.0.1:5001
    - http://127.0.0.1:5002
  timeout: 1s # ms, s, min, h
  keep_alive:
    max_idle_connections: 100 # 0 means no limit
    idle_connection_timeout: 30s # maximum amount of time an idle connection will remain idle before closing itself. (0s means no limit)


health_check:
  endpoint: /health_check
  expected_status_code: 200
  interval: 10s
  timeout: 2s
